---
name: Validate YAML

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual workflow invocation from the Github Actions UI

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920  # v2.20.0
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: yamllint -c .yamllint.yml .
